In [1]:
import pandas as pd
import os

In [2]:
path = '/home/alvaro/Área de Trabalho/Engenharia de Computacao/TCC/Base de dados/Base2/Dados/'

In [3]:
df1 = pd.read_csv('Base_de_dados_BIOMA10.csv')
df2 = pd.read_csv('Base_de_dados_LABIM22.csv')
df3 = pd.read_csv('Base_de_dados_LABIM40.csv')
df4 = pd.read_csv('Base_de_dados_LABIM44.csv')

In [11]:
df = pd.DataFrame()
df = pd.concat([df,df1])
df = pd.concat([df,df2])
df = pd.concat([df,df3])
df = pd.concat([df,df4])

In [12]:
df

,A,C,G,T,AA,AC,AG,AT,CA,CC,...,minimum_ORF_length,std_ORF_length,average_ORF_length,cv_ORF_length,maximum_GC_content_ORF,minimum_GC_content_ORF,std_GC_content_ORF,average_GC_content_ORF,cv_GC_content_ORF,class
0,0.267119,0.232625,0.233145,0.267110,0.092247,0.046173,0.052578,0.076122,0.061875,0.051736,...,6,286.218272,110.962563,2.579413,79.487179,5.555556,10.327820,43.044068,0.239936,Bioma10
0,0.267447,0.232304,0.232049,0.268200,0.092342,0.046143,0.052464,0.076498,0.061931,0.051617,...,6,282.460302,110.590899,2.554101,81.481481,6.666667,10.363506,42.909372,0.241521,LABIM22
0,0.267417,0.232406,0.232360,0.267816,0.092422,0.046153,0.052505,0.076338,0.061879,0.051668,...,6,286.264309,110.436471,2.592117,79.487179,5.555556,10.357896,42.913558,0.241367,LABIM40
0,0.268351,0.231591,0.231760,0.268299,0.092916,0.046279,0.052594,0.076561,0.061942,0.051376,...,6,286.281696,110.546257,2.589700,79.487179,5.555556,10.359707,42.749512,0.242335,LABIM44

In [13]:
df.to_csv('Base_final.csv', index=False)